import { ASSET_MODEL_VERSION, normalizeAsset } from "./assets.js";

const ORIGINAL_LICENSE = {
  type: "original",
  attribution: "MusiCollab demo content — generated by the MusiCollab project",
  distribution: "attribution-required",
  notice: "Demo content is original project material; retain this attribution if redistributed.",
  url: "https://github.com/pratiksk/MusiCollab"
};

const DEMO_ASSETS = [
  { id: "demo-track-drums", type: "track", name: "Demo Drum Kit", tags: ["demo", "drums"], bpm: 118, key: "C", duration: 8, origin: "bundled-demo", license: ORIGINAL_LICENSE },
  { id: "demo-instrument-drums", type: "instrument", name: "Demo Drums", tags: ["demo", "synth"], parameters: { voiceCount: 8, character: 0.35 }, license: ORIGINAL_LICENSE },
  { id: "demo-instrument-bass", type: "instrument", name: "Demo Bass Pulse", tags: ["demo", "bass"], parameters: { voiceCount: 1, cutoff: 0.42 }, license: ORIGINAL_LICENSE },
  { id: "demo-loop-bass", type: "loop", name: "Demo Bass Pulse", tags: ["demo", "loop"], bars: 4, bpm: 118, key: "Am", duration: 8, quantization: "bar", license: ORIGINAL_LICENSE },
  { id: "demo-sample-chops", type: "sample", name: "Demo Sample Chops", tags: ["demo", "sample"], duration: 2, sampleRate: 44100, channels: 1, slices: [{ id: "demo-slice-1", name: "Chop 1", start: 0, end: 0.5 }, { id: "demo-slice-2", name: "Chop 2", start: 0.5, end: 1 }, { id: "demo-slice-3", name: "Chop 3", start: 1, end: 1.5 }, { id: "demo-slice-4", name: "Chop 4", start: 1.5, end: 2 }], license: ORIGINAL_LICENSE },
  { id: "demo-scene-default", type: "scene", name: "Demo Opening Scene", tags: ["demo", "scene"], trackIDs: ["demo-track-drums", "demo-loop-bass"], license: ORIGINAL_LICENSE }
];

export function createDemoLibrary() {
  const library = { modelVersion: ASSET_MODEL_VERSION, tracks: [], instruments: [], loops: [], samples: [], scenes: [], slices: [] };
  for (const source of DEMO_ASSETS) {
    const result = normalizeAsset(source);
    if (!result.error) library[`${result.asset.type}s`].push(result.asset);
  }
  return library;
}

export { DEMO_ASSETS };
